entornoFamFeed/projectFamFeed/famFeed/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('', TablonListView.as_view(), name='principal'),
    path('crearTablon/', TablonCreateView.as_view(), name='crearTablon'),
    path('detalle/<int:pk>', TablonDetailView.as_view(), name='detalle'),
    path('agregarUsuarioTablon/<int:pk>', views.AgregarUsuarioTablonView.as_view(), name='agregarUsuarioTablon'),
    path('crearRecuerdo/<int:pk>', RecuerdoCreateView.as_view(), name='crearRecuerdo'),
    path('detalleRecuerdo/<int:pk>', RecuerdoDetailView.as_view(), name='detalleRecuerdo'),
    path('eliminarComentario/<int:comentario_id>/', EliminarComentarioView.as_view(), name='eliminarComentario'),
]

entornoFamFeed/projectFamFeed/projectFamFeed/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('famFeed.urls')),
    path('cuentas/', include('registration.urls')),#El que irá a registro
    path('cuentas/', include('django.contrib.auth.urls')), #El que irá a login
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entornoFamFeed/projectFamFeed/registration/urls.py
from django.urls import path
from .views import RegistroView

urlpatterns = [
    path('registro/', RegistroView.as_view(), name='registro'),
]

entornoFamFeed/projectFamFeed/famFeed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tablon(models.Model):
    nombre = models.CharField(max_length=30)
    imagen = models.ImageField(verbose_name='fotoTablon', upload_to='famFeed', null=True)
    creador = models.ForeignKey(User, verbose_name='creador', on_delete=models.CASCADE)
    usuarios = models.ManyToManyField(User, related_name='tablones', verbose_name='usuarios')

    class Meta:
        verbose_name = 'tablon'
        verbose_name_plural = 'tablones'

class Recuerdo(models.Model):
    titulo = models.CharField(max_length=30)
    imagenRecuerdo = models.ImageField(verbose_name='imagenRecuerdo', upload_to='famFeedRecuerdos', null=True)
    texto = models.CharField(max_length=1000)
    autor = models.ForeignKey(User, verbose_name='autor', on_delete=models.CASCADE)
    tablon = models.ForeignKey(Tablon, related_name='recuerdos',on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'recuerdo'
        verbose_name_plural = 'recuerdos'

class Comentario(models.Model):
    cuerpo = models.CharField(max_length=50)
    autor = models.ForeignKey(User, verbose_name='autor', on_delete=models.CASCADE)
    recuerdo = models.ForeignKey(Recuerdo, related_name='comentarios',on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comentario'
        verbose_name_plural = 'comentario'

entornoFamFeed/projectFamFeed/famFeed/forms.py
from django import forms
from .models import *

class newComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['cuerpo']
        labels = {
            'cuerpo': 'Comentario',
        }

class newTablonForm(forms.ModelForm):
    class Meta :
        model = Tablon
        fields = ['nombre', 'imagen']
        labels = {
            'nombre' : 'Título del tablón',
            'imagen' : 'Imagen del tablón'
        }

class newRecuerdoForm(forms.ModelForm):
    texto = forms.CharField(widget=forms.Textarea(attrs={'rows': 8}))

    class Meta :
        model = Recuerdo
        fields = ['titulo', 'imagenRecuerdo', 'texto', ]
        labels = {
            'titulo' : 'Título del recuerdo',
            'imagenRecuerdo' : 'Imagen del recuerdo',
            'texto' : 'Descripción del recuerdo'
        }

entornoFamFeed/projectFamFeed/famFeed/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import never_cache
from .models import *
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView


@never_cache
def logout_view(request):
    logout(request)
    return redirect('login')

class TablonListView(LoginRequiredMixin, ListView):
    login_url = 'cuentas/login'
    model = Tablon
    success_url = reverse_lazy('principal')

    def get_queryset(self):
        queryset = super().get_queryset()
        usuario_actual = self.request.user
        queryset = queryset.filter(usuarios=usuario_actual)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tablones'] = self.get_queryset()
        return context
    
class TablonCreateView(LoginRequiredMixin, CreateView):

    login_url = 'cuentas/login'
    model = Tablon
    form_class = newTablonForm
    success_url = reverse_lazy('principal')

    def form_valid(self, form):
        form.instance.creador = self.request.user
        # Guardar el tablón y establecer la relación con el usuario
        tablon = form.save()
        tablon.usuarios.add(self.request.user)
        return super().form_valid(form)
    
class TablonDetailView(LoginRequiredMixin, DetailView):
    model = Tablon
    context_object_name = 'tablon'
    login_url = 'cuentas/login'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tablon = self.get_object()
        context['recuerdos'] = tablon.recuerdos.all()
        return context

class AgregarUsuarioTablonView(LoginRequiredMixin, TemplateView):

    template_name = 'agregar_usuario_tablon.html'
    
    def post(self, request, pk):
        try:
            tablon = get_object_or_404(Tablon, pk=pk)
            username = request.POST.get('nombre')
            user = get_object_or_404(User, username=username)
            # Agregar el usuario al tablón utilizando el campo ManyToManyField
            tablon.usuarios.add(user)
            return redirect('detalle', pk=tablon.pk)
        except:
            return self.get(request, pk=tablon.pk)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega los datos adicionales al contexto
        tablon_id = kwargs['pk']
        tablon = Tablon.objects.get(id=tablon_id)
        context['tablon'] = tablon
        return context
    
class RecuerdoCreateView(LoginRequiredMixin, CreateView):

    login_url = 'cuentas/login'
    model = Recuerdo
    form_class = newRecuerdoForm
    success_url = reverse_lazy('principal')

    def form_valid(self, form):
        form.instance.autor = self.request.user
        tablon_id = self.kwargs['pk']
        form.instance.tablon_id = tablon_id 
        recuerdo = form.save()
        return super().form_valid(form)
    
class RecuerdoDetailView(LoginRequiredMixin, DetailView):
    model = Recuerdo
    context_object_name = 'recuerdo'
    login_url = 'cuentas/login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recuerdo = self.get_object()
        context['comentarios'] = recuerdo.comentarios.all()
        context['comentario_form'] = newComentarioForm()
        return context
    
    def post(self, request, *args, **kwargs):
        recuerdo = self.get_object()
        comentario_form = newComentarioForm(request.POST)

        if comentario_form.is_valid():
            comentario = comentario_form.save(commit=False)
            comentario.recuerdo = recuerdo
            comentario.autor = request.user
            comentario.save()
        
        return redirect('detalleRecuerdo', pk=recuerdo.pk)

class EliminarComentarioView(View):
    def post(self, request, comentario_id):
        comentario = get_object_or_404(Comentario, id=comentario_id)
        
        # Verificar si el usuario actual es el autor del comentario
        if comentario.autor == request.user:
            comentario.delete()
        
        # Redireccionar a la página de detalle del recuerdo
        return redirect('detalleRecuerdo', pk=comentario.recuerdo.id)

entornoFamFeed/projectFamFeed/famFeed/templates/famFeed/recuerdo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css">
    <title>Recuerdo Famfeed</title>
    <style>
        /*------------------------------------------------------------*/
        /*GLOBALES*/
        :root{
            --fuente:'Montserrat', sans-serif;
            --blanco:#ffffff;
            --gris: #e1e1e1;
            --negro: #000000;
            --basico: #FCF2EA;
            --primario:#FF9126;
            --secundario:#AAD7D5; 
            --primarioOscuro:#DB5933;
            --secundarioOscuro:#58A9A2;
            
        }
        html{
            box-sizing: border-box;
            font-size: 62.5%;
            width: 100%;
            height: 100%;
        }
        *, *:before, *:after{
            box-sizing: inherit;
        }
        body{
            font-family: var(--fuente);
            font-size: 1.6rem;
            line-height: 2;
            margin:0px;
            background-color: var(--basico);
            text-align: center;
            display: flex;
            flex-direction: column;
        }
        /*------------------------------------------------------------*/
        /*CABECERA*/

        header{
            height: 20rem;
            background-color: var(--secundario);
        }
        .titulo{
            margin-top: 0;
            color: var(--primario);
            font-size: 10rem;
            font-weight: lighter; 
            text-align: center;
        }
        /*------------------------------------------------------------*/
        /*CUERPO*/
        h1{
            color: var(--secundarioOscuro);
            font-size: 50px;
            margin: 0;
        }
        p{
            color: var(--negro);
            font-size: 20px;
        }
        a{
            text-decoration: none;
        }
        label{
        font-size: 23px;
        font-weight: bold;
        }
        .texto{
            align-items: center;
            justify-content: center;
            display: flexbox;
            padding-left: 50px;
            padding-right: 50px;
        }
        input{
        color: var(--secundarioOscuro);
        margin: 1rem;
        padding: 20px;
        width: 50rem;
        border: 0 solid ;
        border-radius: 20px;
        font-size: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
        }
        .btnComentario{
        background-color: var(--primarioOscuro);
        width: 25rem;
        color: var(--basico);
        margin-bottom: 5rem;
        border-radius: 50px;
        border: 0px solid;
        font-size: 20px;
        font-family: var(--fuente);
        text-transform: uppercase;
        padding: 4px;
        }
        .btnEliminar{
        text-transform: uppercase;
        background-color: var(--basico);
        color: var(--primarioOscuro);
        margin-bottom: 5rem;
        border: 0px solid;
        font-size: 15px;
        font-family: var(--fuente);
        }
        hr{
        width: 90%;
        margin: 5rem;
        }
        ul{
        list-style: none;
        margin-bottom: 5rem;
        }
        li{
        font-style: italic;
        margin: 20px;
        }
        
        h2{
        text-decoration: underline;
        }

        /*------------------------------------------------------------*/
        /*PIE DE PAGINA*/
        footer{
            margin-top: auto;
            width: 100%;
            height: 5rem;
            background-color: var(--secundario);
            
        }
        img{
            max-width: 60%;
        }
    </style>
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <h1 class="navbar-brand "><a href="{% url 'principal' %}" class="titulo">FAMFEED</a></h1>
          </div>
        </nav>
    </header>

    <main>
        <h1>{{ recuerdo.titulo }}</h1>
        <p>
            <img src="/media/{{ recuerdo.imagenRecuerdo }}" alt="imagen">
        </p>
        <div class="texto">
            <p class="parrafo">{{ recuerdo.texto }}</p>
        </div>
        <br>
        
        
        <hr>
        <div>
            <h2>Comentarios</h2>
            <ul>
                {% for comentario in comentarios %}
                <li>{{ comentario.cuerpo }} -- {{ comentario.autor }}
                    {% if comentario.autor.id == request.user.id %}
                        <form method="POST" action="{% url 'eliminarComentario' comentario.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="comentario_id" value="{{ comentario.id }}">
                            <button type="submit" class="btnEliminar">Eliminar</button>
                        </form>
                    {% endif %}
                </li>
                    
                {% endfor %}
            </ul>
        </div>
        <div>
            <div id="comentario-form-container">
                <form method="post">
                    {% csrf_token %}
                    {{ comentario_form.as_p }}
                    <br>
                    <button type="submit" class="btnComentario">Añadir comentario</button>
                </form>
            </div>
        </div>
    </main>

</body>

</html> 

entornoFamFeed/projectFamFeed/famFeed/templates/famFeed/recuerdo_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css">
    <title>Nuevo Recuerdo Famfeed</title>
    <style>
        /*------------------------------------------------------------*/
        /*GLOBALES*/
        :root{
            --fuente:'Montserrat', sans-serif;
            --blanco:#ffffff;
            --gris: #e1e1e1;
            --negro: #000000;
            --basico: #FCF2EA;
            --primario:#FF9126;
            --secundario:#AAD7D5; 
            --primarioOscuro:#DB5933;
            --secundarioOscuro:#58A9A2;
            
        }
        html{
            box-sizing: border-box;
            font-size: 62.5%;
            width: 100%;
            height: 100%;
        }
        *, *:before, *:after{
            box-sizing: inherit;
        }
        body{
            font-family: var(--fuente);
            font-size: 1.6rem;
            line-height: 2;
            margin:0px;
            background-color: var(--basico);
            text-align: center;
            display: flex;
            flex-direction: column;
        }
        /*------------------------------------------------------------*/
        /*CABECERA*/

        header{
            height: 20rem;
            background-color: var(--secundario);
        }
        .titulo{
            margin-top: 0;
            color: var(--primario);
            font-size: 10rem;
            font-weight: lighter; 
            text-align: center;
        }
        /*------------------------------------------------------------*/
        /*CUERPO*/
        h1{
            color: var(--secundarioOscuro);
            font-size: 50px;
            margin:0;
        }  
        label{
            color: var(--secundarioOscuro);
            font-size: 25px;
        }

        input{
            color: var(--secundarioOscuro);
            margin: 1rem;
            padding: 20px;
            width: 50rem;
            border: 0 solid ;
            border-radius: 20px;
            font-size: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
        }
        .btnImg{
            background-color: var(--secundario);
            color: var(--primarioOscuro);
            border: 0px solid ;
            border-radius: 50px;
            font-family: var(--fuente);
            text-transform: uppercase;
            width: 30rem;
            font-size: 20px;
        }
        button{
            background-color: var(--primarioOscuro);
            color: var(--basico);
            border: 0px solid var(--secundario);
            border-radius: 50px;
            font-family: var(--fuente);
            text-transform: uppercase;
            width: 20rem;
            font-size: 20px;
        }
        textarea{
            color: var(--secundarioOscuro);
            margin: 1rem;
            padding: 20px;
            width: 50rem;
            border: 0 solid ;
            border-radius: 20px;
            font-size: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
        }
        a{
            text-decoration: none;
        }
        form{
            display:block;
        }
        /*------------------------------------------------------------*/
        /*PIE DE PAGINA*/
        footer{
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 5rem;
            background-color: var(--secundario);
            
        }
    </style>
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <h1 class="navbar-brand "><a href="{% url 'principal' %}" class="titulo">FAMFEED</a></h1>
          </div>
        </nav>
    </header>

    <main>
        <h1>Nuevo Recuerdo</h1>

        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }}
                    <br>
                    {{ field }}
                </div>
                {% endfor %}
                
                <!-- {% csrf_token %}
                {{ form.as_p }} -->
                <br>
                <button type="submit">Crear Recuerdo</button>
                <br><br>
            </form>
        </div>
    </main>
</body>

</html> 

entornoFamFeed/projectFamFeed/famFeed/templates/famFeed/tablon_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css">
    <title>Recuerdos Famfeed</title>
    <style>
        /*------------------------------------------------------------*/
        /*GLOBALES*/
        :root{
            --fuente:'Montserrat', sans-serif;
            --blanco:#ffffff;
            --gris: #e1e1e1;
            --negro: #000000;
            --basico: #FCF2EA;
            --primario:#FF9126;
            --secundario:#AAD7D5; 
            --primarioOscuro:#DB5933;
            --secundarioOscuro:#58A9A2;
            
        }
        html{
            box-sizing: border-box;
            font-size: 62.5%;
            width: 100%;
            height: 100%;
        }
        *, *:before, *:after{
            box-sizing: inherit;
        }
        body{
            font-family: var(--fuente);
            font-size: 1.6rem;
            line-height: 2;
            margin:0px;
            background-color: var(--basico);
            text-align: center;
            display: flex;
            flex-direction: column;
        }
        /*------------------------------------------------------------*/
        /*CABECERA*/

        header{
            height: 20rem;
            background-color: var(--secundario);
            
        }
        .titulo{
            margin-top: 0;
            color: var(--primario);
            font-size: 10rem;
            font-weight: lighter; 
            text-align: center;
        }
        /*------------------------------------------------------------*/
        /*CUERPO*/
        h1{
            color: var(--secundarioOscuro);
            font-size: 50px;
            margin-top: 1rem;
        }
        p{
            color: var(--secundarioOscuro);
            font-size: 30px;
            margin: 20px;
        }   
        p{
            color: var(--negro);
            font-size: 20px;
        }
        #usuarioDiv {
            display: none;
            background: var(--secundarioOscuro); /* Color de fondo */
            position: absolute; /* Posición absoluta para aparecer debajo */
            top: 26rem; /* Espacio desde la parte superior */
            right: 0; /* Alineación a la izquierda */
            width: 25rem; /* Ancho del div */
            padding: 10px; /* Espacio interno */
            box-sizing: border-box; /* Incluir el padding en el ancho total */
            color: var(--primarioOscuro);
        }  
        h2{
        text-align: center;
        }
        a{
            text-decoration: none;
            color: var(--primarioOscuro);
            text-transform: uppercase;
        } 
        .sesion{
            color: var(--basico);
            font-size: 20px;
            background-color: var(--primarioOscuro);
            padding: 5px;
            border-radius: 50px;
        }
        /*------------------------------------------------------------*/
        /*CUERPO*/
        .grid-container {
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-template-rows: 1fr 1fr;
            gap: 10px;
            margin-bottom: 10rem;
        }

        .grid-item {
            background-color: var(--secundario);
            padding: 20px;
            display: flex;
            text-align: center;
        }
        .grid-item img {
            margin-right: 10px;
        }
        .grid-item h2 {
            margin-top: 0;
        }
        .tablon{
        margin-bottom: 2rem ;
        }
        img{
        max-width: 50%;
        }
        /*------------------------------------------------------------*/
        /*MENU*/
        .menu {
            display: flex;
            justify-content: space-between;
            background-color: var(--secundarioOscuro);
            height: 8rem;
            font-size: 24px;
            padding: 2rem;
        }
        .menu .izquierda {
            margin-right: auto;
        }
        .menu .derecha {
            display: flex;
            flex-direction: row;
            justify-content: flex-end;
        }
        .titulo{
        color: var(--primario);
        }

        .btnUsuario{
        background-color: var(--primarioOscuro);
        color: var(--basico);
        border: 0px solid var(--secundario);
        border-radius: 50px;
        font-family: var(--fuente);
        text-transform: uppercase;
        width: 20rem;
        font-size: 12px;
        margin-right: 5px;
        }

        label{
        font-size: 23px;
        font-weight: bold;
        text-decoration: underline;
        }

        input{
        color: var(--secundarioOscuro);
        margin: 1rem;
        padding: 20px;
        width: 50rem;
        border: 0 solid ;
        border-radius: 20px;
        font-size: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
        }

        .btnComentario{
        background-color: var(--primarioOscuro);
        width: 25rem;
        color: var(--basico);
        }

        hr{
        width: 90%;
        margin: 5rem;
        }
        ul{
        list-style: none;
        margin-bottom: 5rem;
        }
        li{
        font-style: italic;
        margin: 20px;
        }
        /*------------------------------------------------------------*/
        /*PIE DE PAGINA*/
        footer{
            margin-top: auto;
            width: 100%;
            height: 5rem;
            background-color: var(--secundario);
            
        }
    </style>
</head>
<body>
    <!--CABECERA-->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container d-flex justify-content-between"">
            <h1 class="navbar-brand "><a href="{% url 'principal' %}" class="titulo">FAMFEED</a></h1>
          </div>
        </nav>
    </header>
    <!--MENU-->
    <section>
        <div class="menu">
            <div class="izquierda"><a href="{% url 'crearRecuerdo' tablon.id %}">Crear Nuevo Recuerdo</a></div>
            <div class="derecha"><a href="#" onclick="toggleDivVisibility()">Usuario</a></div>
            <div id="usuarioDiv" style="display: none;">
                <div>
                    <h4>Nombre:</h4>
                    <p>{{ user.username }}</p>
                </div>
                <div>
                    <h4>Correo:</h4>
                    <p>{{ user.email }}</p>
                </div>               
                <a href="{% url 'logout' %}" class="sesion">Cerrar sesión</a>
              </div>
          </div>
          </div>
    </section>
    <!--CUERPO-->
    <main>
        <div class="tablon">
            <h1 class="mb-4">{{ tablon.nombre }}</h1>
            {% if request.user.id == tablon.creador.id %}
                <a href="{% url 'agregarUsuarioTablon' tablon.id %}">Agregar usuario al tablón</a>
            {% endif %}
        </div>
    
        <div class="grid-container">
            {% for recuerdo in recuerdos %}
                <div class="grid-item">
                    <a href="{% url 'detalleRecuerdo' recuerdo.id %}">
                        <img src="/media/{{ recuerdo.imagenRecuerdo }}" alt="imagen">
                        <h4 class="tituloTablon">Nombre del recuerdo: {{ recuerdo.titulo }}</h4>
                        <p class="creadorTablon">Autor: {{ recuerdo.autor.username }}</p>
                        <!-- Puedes acceder a otros atributos del recuerdo aquí -->
                    </a>
                </div>
            {% endfor %}
        </div>
    </main>

    <!--JAVASCRIPT-->
    <script>
        function toggleDivVisibility() {
          var usuarioDiv = document.getElementById("usuarioDiv");
          if (usuarioDiv.style.display === "none") {
            usuarioDiv.style.display = "block";
          } else {
            usuarioDiv.style.display = "none";
          }
        }
    </script>

</body>

</html> 

entornoFamFeed/projectFamFeed/templates/agregar_usuario_tablon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/css/bootstrap.min.css">
    <title>Modificar Tablón Famfeed</title>
    <style>
        /*------------------------------------------------------------*/
        /*GLOBALES*/
        :root{
            --fuente:'Montserrat', sans-serif;
            --blanco:#ffffff;
            --gris: #e1e1e1;
            --negro: #000000;
            --basico: #FCF2EA;
            --primario:#FF9126;
            --secundario:#AAD7D5; 
            --primarioOscuro:#DB5933;
            --secundarioOscuro:#58A9A2;
            
        }
        html{
            box-sizing: border-box;
            font-size: 62.5%;
            width: 100%;
            height: 100%;
        }
        *, *:before, *:after{
            box-sizing: inherit;
        }
        body{
            font-family: var(--fuente);
            font-size: 1.6rem;
            line-height: 2;
            margin:0px;
            background-color: var(--basico);
            text-align: center;
            display: flex;
            flex-direction: column;
        }
        /*------------------------------------------------------------*/
        /*CABECERA*/

        header{
            height: 20rem;
            background-color: var(--secundario);
        }
        .titulo{
            margin-top: 0;
            color: var(--primario);
            font-size: 10rem;
            font-weight: lighter; 
            text-align: center;
        }
        /*------------------------------------------------------------*/
        /*CUERPO*/
        h1{
            color: var(--secundarioOscuro);
            font-size: 50px;
            margin:0;
        }  
        .usuario{
            font-size: 30px;
        }
        label{
            color: var(--secundarioOscuro);
            font-size: 25px;
        }
        a{
            text-decoration: none;
        }
        input{
            color: var(--secundarioOscuro);
            margin: 1rem;
            padding: 20px;
            width: 50rem;
            border: 0 solid ;
            border-radius: 20px;
            font-size: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
        }
        button{
            background-color: var(--primarioOscuro);
            color: var(--basico);
            border: 0px solid var(--secundario);
            border-radius: 50px;
            font-family: var(--fuente);
            text-transform: uppercase;
            width: 20rem;
            font-size: 20px;
        }
        /*------------------------------------------------------------*/
        /*PIE DE PAGINA*/
        footer{
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 5rem;
            background-color: var(--secundario);
            
        }
    </style>
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <h1 class="navbar-brand "><a href="{% url 'principal' %}" class="titulo">FAMFEED</a></h1>
          </div>
        </nav>
    </header>

    <main>
        <div class="container mt-5">
            <div>
                <h1 class="usuario">Agregar Usuario al Tablón "{{ tablon.nombre }}"</h1><br>
                <form method="POST" action="{% url 'agregarUsuarioTablon' pk=tablon.id %}">
                    {% csrf_token %}
                    <label for="id_nombre">Nombre de Usuario:</label>
                    <br>
                    <input type="text" id="id_nombre" name="nombre" required>
                    <br><br>
                    <button type="submit">Agregar Usuario</button>
                </form>
            </div>
        </div>
    </main>

</body>

</html> 